//TODO

export const GET_TODO_FETCHING = 'GET_TODO_FETCHING'
export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS'
export const CREATE_TODO_FETCHING = 'CREATE_TODO_FETCHING'
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS'
export const REMOVE_TODO_BY_ID_FETCHING = 'REMOVE_TODO_BY_ID_FETCHING'
export const REMOVE_TODO_BY_ID_SUCCESS = 'REMOVE_TODO_BY_ID_SUCCESS'
export const UPDATE_TODO_BY_ID_FETCHING = 'UPDATE_TODO_BY_ID_FETCHING'
export const UPDATE_TODO_BY_ID_SUCCESS = 'UPDATE_TODO_BY_ID_SUCCESS'
export const ACTIVE_TODO_FETCHING = 'ACTIVE_TODO_FETCHING'
export const ACTIVE_TODO_SUCCESS = 'ACTIVE_TODO_SUCCESS'
export const COMPLETED_TODO_FETCHING = 'COMPLETED_TODO_FETCHING'
export const COMPLETED_TODO_SUCCESS = 'COMPLETED_TODO_SUCCESS'

// User
//export const GET_USER_FETCHING = 'GET_USER_FETCHING'
//export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'


